name: Arduino CI

on:
  push:
    branches:
      - main
      - devel
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - ".github/**"
      - "**/*.adoc"
      - "**/*.md"
      - "**/*.txt"
      - "library.*"
  pull_request:

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        boards:
          - arduino:avr:nano
          - arduino:megaavr:nona4809
          - arduino:samd:nano_33_iot
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Compile Examples
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.boards }}
          sketch-paths: |
            - examples

#      - name: Compile Example for ESP32
#        uses: espressif/esp-idf-ci-action@latest
#        with:
#          target: esp32dev
#          path: 'libcli/examples/cli'

      - name: Compile Example for STM32
        uses: stm32duino/actions/compile-examples@main
        with:
          board-pattern: 'NUCLEO_F411RE'
