name: C/C++ CI

on:
  push:
    branches:
      - main
      - devel
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - ".github/**"
      - "**/*.adoc"
      - "**/*.md"
      - "**/*.txt"
      - "library.*"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build test and run
      run: git submodule update --init; make -C test test
